version: '3'

services:
  master:
    image: redis:3
    networks:
      debug_client_service_network:
        aliases:
          - redis-master-service
  slave:
    image: redis:3
    command: redis-server --slaveof redis-master 6379
    links:
      - master:redis-master
    networks:
      debug_client_service_network:
        aliases:
          - redis-slave-service
  sentinel:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - master:redis-master
      - slave
    networks:
      debug_client_service_network:
        aliases:
          - sentinel-service

networks:
  debug_client_service_network:
    external:
      name: armor-backend_debug_core_backend_network
